#!/bin/sh

kubectl stop -f redis.yml
kubectl stop -f redis-service.yml
kubectl stop -f cart.yml
kubectl stop -f cart-service.yml
kubectl stop -f cart-controller.yml
kubectl stop -f mongodb.yml
kubectl stop -f mongodb-service.yml
kubectl stop -f product.yml
kubectl stop -f product-service.yml
kubectl stop -f product-controller.yml
kubectl stop -f navigation.yml
kubectl stop -f navigation-service.yml
kubectl stop -f navigation-controller.yml
kubectl stop -f shop.yml
kubectl stop -f shop-service.yml
kubectl stop -f catalog.yml
kubectl stop -f catalog-service.yml
kubectl stop -f catalog-controller.yml

kubectl delete -f redis.yml
kubectl delete -f redis-service.yml
kubectl delete -f cart.yml
kubectl delete -f cart-service.yml
kubectl delete -f cart-controller.yml
kubectl delete -f mongodb.yml
kubectl delete -f mongodb-service.yml
kubectl delete -f product.yml
kubectl delete -f product-service.yml
kubectl delete -f product-controller.yml
kubectl delete -f navigation.yml
kubectl delete -f navigation-service.yml
kubectl delete -f navigation-controller.yml
kubectl delete -f shop.yml
kubectl delete -f shop-service.yml
kubectl delete -f catalog.yml
kubectl delete -f catalog-service.yml
kubectl delete -f catalog-controller.yml
