#!/bin/sh
kubectl update -f redis.yml
kubectl update -f redis-service.yml
kubectl update -f cart.yml
kubectl update -f cart-controller.yml
kubectl update -f cart-service.yml
kubectl update -f mongodb.yml
kubectl update -f mongodb-service.yml
kubectl update -f product.yml
kubectl update -f product-controller.yml
kubectl update -f product-service.yml
kubectl update -f navigation.yml
kubectl update -f navigation-controller.yml
kubectl update -f navigation-service.yml
kubectl update -f shop.yml
kubectl update -f shop-service.yml
kubectl update -f catalog.yml
kubectl update -f catalog-controller.yml
kubectl update -f catalog-service.yml
