# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :java do |java|
    java.vm.box = "precise64"
    java.vm.provider "virtualbox" do |v|
      v.name = "java-node"
      v.customize ["modifyvm", :id, "--memory", "512"]
    end
    java.vm.network :private_network, ip: "10.211.55.105"
    java.vm.hostname = "java-node"
    java.vm.provision :shell, :path => "provision/java.sh"
  end
end
