@startuml
scale 1.5

node "Microservice Node" {
[Frontend] -down-> REST

REST -down- [Product Service]
REST -down- [Navigation Service]
REST -down- [Card Service]

[Product Service] -down-> MongoDB
[Navigation Service] -down-> MongoDB
[Card Service] -down-> Redis
}

node "Monolith Node" {
[Shop Application] -down-> MongoDB
[Shop Application] -down-> REST
}

database MongoDB {
}

database Redis {
}

@enduml

