name 'richardc-datacat'
version '0.6.1'
source 'git://github.com/richardc/puppet-datacat.git'
author 'richardc'
license 'Apache 2.0'
summary 'Puppet type for handling data fragments'
description 'A pair of types for handling data fragments and templating'
project_page 'https://github.com/richardc/puppet-datacat'
