#!/bin/sh
set -e

chmod +x /usr/share/shop/recommendation/createRecommendations.sh
chmod +x /usr/share/shop/recommendation/recommendation.R
sudo touch /var/log/recommendation.log
Rscript  /usr/share/shop/recommendation/installDependencies.R >> /var/log/recommendation.log
echo "*/5 * * * * /usr/share/shop/recommendation/createRecommendations.sh >> /var/log/recommendation.log" >> /etc/crontab
service cron restart