name    'deric-zookeeper'
version '0.3.3'
source 'https://github.com/deric/puppet-zookeeper'
author 'Tomas Barton'
license 'Apache License, Version 2.0'
summary 'Module for managing Apache Zookeeper'
description 'ZooKeeper is a centralized service for maintaining configuration information, naming, providing distributed synchronization, and providing group services.'
project_page 'https://github.com/deric/puppet-zookeeper'

dependency 'puppetlabs/stdlib', '>= 2.3.3'
dependency 'richardc/datacat'
