#!/bin/sh

kubectl stop -f redis.json
kubectl stop -f redis-service.json
kubectl stop -f cart.json
kubectl stop -f cart-service.json
kubectl stop -f cart-controller.json
kubectl stop -f mongodb.json
kubectl stop -f mongodb-service.json
kubectl stop -f product.json
kubectl stop -f product-service.json
kubectl stop -f product-controller.json
kubectl stop -f navigation.json
kubectl stop -f navigation-service.json
kubectl stop -f navigation-controller.json
kubectl stop -f shop.json
kubectl stop -f shop-service.json
kubectl stop -f catalog.json
kubectl stop -f catalog-service.json
kubectl stop -f catalog-controller.json

kubectl delete -f redis.json
kubectl delete -f redis-service.json
kubectl delete -f cart.json
kubectl delete -f cart-service.json
kubectl delete -f cart-controller.json
kubectl delete -f mongodb.json
kubectl delete -f mongodb-service.json
kubectl delete -f product.json
kubectl delete -f product-service.json
kubectl delete -f product-controller.json
kubectl delete -f navigation.json
kubectl delete -f navigation-service.json
kubectl delete -f navigation-controller.json
kubectl delete -f shop.json
kubectl delete -f shop-service.json
kubectl delete -f catalog.json
kubectl delete -f catalog-service.json
kubectl delete -f catalog-controller.json
