name    'meltwater-marathon'
version '0.1.2'
source 'https://github.com/mesosphere/marathon'
author 'meltwater'
license 'Apache License, Version 2.0'
summary 'Puppet Module for Mesos Marathon'
description 'Puppet Module for Mesos Marathon'
project_page 'https://github.com/meltwater/puppet-marathon'

dependency 'puppetlabs/stdlib', '>= 2.2.0'
dependency 'camptocamp-archive'
