#! /bin/sh

source /etc/default/cart

if [ `id -u` -ne 0 ]; then
    echo "You need root privileges to run this script"
    exit 1
fi

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/etc/init.d
. /lib/lsb/init-functions

if [ -r /etc/default/cart ]; then
        . /etc/default/cart
fi

case "$1" in
    start)
        log_daemon_msg "Starting cart service"
        nohup /usr/share/shop/cart/bin/cart > /var/log/cart.log 2>&1 &
        sleep 1
        log_end_msg 0 || true
        ;;
    restart|reload|force-reload)
        log_daemon_msg "Restart cart service"
        kill `ps ax|grep cart|sed 's/\(.*\)pts.*/\1/g'|head -n 1`
        nohup /usr/share/shop/cart/bin/cart > /var/log/cart.log 2>&1 &
        sleep 1
        log_end_msg 0 || true
        ;;
    stop)
        kill `ps ax|grep cart|sed 's/\(.*\)pts.*/\1/g'|head -n 1`
        ;;
    *)
        echo "Usage: $0 start|restart|stop" >&2
        exit 3
        ;;
esac